version: '3'
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
