version: '3.7'
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
    volumes:
    depends_on: wordpress
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
    volumes:
    depends_on: mariadb
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
    volumes:
    restart: always
