version: '3.9'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${CERTS_}:/etc/nginx/certs
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: /requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always


volumes:
  wordpress:
  mariadb:
