version: '3.7'

services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - /home/amaria-m/data/mysql:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - /home/amaria-m/data/wordpress:/var/www/html/wordpress
    networks:
      - inception_network
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - /home/amaria-m/data/wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: on-failure

networks:
  inception_network:
    name: inception