version: '3.9'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${CERTS_}:/etc/nginx/certs
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress:5.7.1-php7.3-apache
    env_file:
      - .env
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mysql:5.7.34
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql


volumes:
  wordpress:
  mariadb:
