CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'amaria-m'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'amaria-m'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';